CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL UNIQUE,
    author_id BIGINT NOT NULL REFERENCES authors(id) ON DELETE CASCADE,
    avg_review NUMERIC(10, 2) NOT NULL DEFAULT 0.0,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);
