name: cd-pipeline

on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-24.04
    needs: [lint, test, build]
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: |
          echo DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }} >> .env
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bookshop:latest
      - name: Trigger Render deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}